image: microsoft/dotnet:2.1-sdk
pipelines:
  custom:
    nuget:
    - step:
        caches:
          - dotnetcore
        script:
          # Restore packages
          - dotnet restore
          # Build project
          - dotnet build --configuration Release
          # Create package
          - dotnet pack MongoDBMigrations/MongoDBMigrations.csproj --configuration ${BUILD_CONFIGURATION}
          # Push generated package(s)
          - dotnet nuget push MongoDBMigrations/bin/${BUILD_CONFIGURATION}/*.nupkg -k ${MYGET_NUGET_APIKEY} -s https://api.nuget.org/v3/index.json